spring.data.mongodb.uri=mongodb+srv://divyanshnarayanm_db_user:database_15com@cluster0.w7jrttp.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=journal
spring.application.name=journal-App
spring.data.mongodb.auto-index-creation=true